WHEEL_UP add volume 2
WHEEL_DOWN add volume -2
Alt+LEFT no-osd add sub-delay -0.1
Alt+RIGHT no-osd add sub-delay 0.1
Ctrl+LEFT no-osd add audio-delay -0.1
Ctrl+RIGHT no-osd add audio-delay 0.1
MBTN_BACK playlist-prev
MBTN_FORWARD playlist-next
