profile=high-quality
gpu-context=wayland
hwdec=vaapi-copy
vo=gpu
save-position-on-quit=yes
keep-open=yes
cursor-autohide=900
osd-bar=yes
osd-duration=1800
osd-font=Noto Sans
osd-font-size=24
sub-auto=fuzzy
sub-font=Noto Sans
sub-scale=0.95
sub-border-size=1.8
volume-max=150
autofit-larger=1280x720
screenshot-directory=~/Pictures
screenshot-template=mpv-%F-%wH.%wM.%wS
screenshot-format=png
