[Unit]
BindsTo=labwc-compositor.service
After=labwc-compositor.service labwc-session.target
ConditionEnvironment=LABWC_SESSION_OWNER=desktop
ConditionEnvironment=WAYLAND_DISPLAY
ConditionEnvironment=XDG_SESSION_TYPE=wayland
PartOf=labwc-session.target

[Install]
WantedBy=labwc-session.target
