[Unit]
# Keep the dispatcher alive for the whole NetworkManager lifecycle and stop it
# only after NetworkManager has completed its final synchronous dispatches.
Before=NetworkManager.service
PartOf=NetworkManager.service

[Service]
ExecStart=
ExecStart=/usr/libexec/nm-dispatcher --persist
