[Unit]
# This late session socket must not precede sockets.target/basic.target.
DefaultDependencies=no
Conflicts=shutdown.target
Before=shutdown.target
ConditionEnvironment=LABWC_SESSION_OWNER=desktop
PartOf=labwc-session.target
Requisite=labwc-session.target
After=labwc-session.target
