[Unit]
Conflicts=getty@tty1.service
Wants=systemd-user-sessions.service systemd-logind.service seatd.service dbus.socket
After=systemd-user-sessions.service systemd-logind.service seatd.service dbus.socket

[Service]
TTYPath=/dev/tty1
StandardInput=tty
SyslogIdentifier=greetd-labwc
StandardOutput=journal
StandardError=journal
