# Managed by unattended-installer.
d /var/cache/ldconfig 0700 root root -
d /var/cache/mullvad-vpn 0755 root root -
d /var/cache/tailscale 0750 root root -
d /var/cache/fontconfig 0755 root root -
d /var/cache/incus 0700 root root -
d /var/cache/incus/resources 0700 root root -
d /var/cache/fwupd 0755 root root -
d /var/cache/fwupdmgr 0755 fwupd-refresh fwupd-refresh -
