[General]
GeoLocale=system
SensitiveInfoMaskOn=true
autoPlayGif=false
captureHDCamera=true
enableMiniWindow=false
enableQmlCache=true
enableTestMode=false
enableWaylandShare=true
flashChatTime=0
forceEnableTrayIcon=false
login_domain=
newMeetingWithVideo=false
playSoundForNewMessage=false
scaleFactor=1
showHowToJoinFromRoom=false
sso_domain=
sso_gov=false
system.audio.type=default
system.audio.type.default.device=
system.audio.type.default.microphone=
system.audio.type.default.speaker=
system.audio.type.usb.device=
system.audio.type.usb.microphone=
system.audio.type.usb.speaker=
upcoming_meeting_header_image=
useSystemTheme=true
