#!/bin/sh

. /lib/partman/lib/base.sh

for dev in $DEVICES/*; do
    [ -d "$dev" ] || continue
    cd "$dev"
    open_dialog PARTITIONS
    while { read_line num id size type fs path name; [ "$id" ]; }; do
        [ "$fs" != free ] || continue
        [ -f "$id/method" ] || continue
        [ -f "$id/acting_filesystem" ] || continue
        filesystem=$(cat "$id/acting_filesystem")
        case "$filesystem" in
            f2fs)
                [ -f "$id/mountpoint" ] || continue
                mountpoint=$(cat "$id/mountpoint")
                options=$(get_mountoptions "$dev" "$id")
                if [ "$mountpoint" = / ]; then
                    pass=1
                else
                    pass=2
                fi
                echo "$path" "$mountpoint" "$filesystem" "$options" 0 "$pass"
                ;;
        esac
    done
    close_dialog
done
