font_family __INSTALLER_LABWC_TERMINAL_FONT_FAMILY__
font_size __INSTALLER_LABWC_TERMINAL_FONT_SIZE__
allow_remote_control socket-only
listen_on unix:${XDG_RUNTIME_DIR}/kitty-labwc
adjust_line_height 0
cursor_shape beam
cursor_blink_interval 0.55
scrollback_lines 10000
wheel_scroll_multiplier 3.0
enable_audio_bell no
confirm_os_window_close 0
remember_window_size no
initial_window_width __INSTALLER_LABWC_TERMINAL_WINDOW_COLUMNS__c
initial_window_height __INSTALLER_LABWC_TERMINAL_WINDOW_ROWS__c
window_padding_width 4
background_opacity __INSTALLER_LABWC_TERMINAL_BACKGROUND_OPACITY__
linux_display_server wayland

foreground #f3ead7
background #111318
selection_foreground #111318
selection_background #ecb860
color0 #1c1f26
color1 #ca5252
color2 #7a9f64
color3 #ecb860
color4 #6f8fb5
color5 #b083c5
color6 #6ca0a3
color7 #e5ddca
color8 #4c515d
color9 #ff6b6b
color10 #98c379
color11 #f3c969
color12 #8aadf4
color13 #cba6f7
color14 #88c0d0
color15 #ffffff
