[Service]
# Lower maintenance priority
Nice=10
IOSchedulingClass=idle
IOSchedulingPriority=7

# fstrim needs privileged FITRIM ioctl access
CapabilityBoundingSet=
CapabilityBoundingSet=CAP_SYS_ADMIN
AmbientCapabilities=
NoNewPrivileges=yes

# Additional compatible hardening
PrivateTmp=yes
ProtectClock=yes
ProtectHostname=yes
ProtectKernelLogs=yes

LockPersonality=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RestrictNamespaces=yes
SystemCallArchitectures=native
