[DEFAULT]
cleanup = automatic
db_url = sqlite:////var/lib/fangfrisch/db.sqlite
integrity_check = sha256
local_directory = /var/lib/clamav
log_level = INFO
log_method = console
max_size = 20MB
on_update_exec = /bin/true
on_update_timeout = 5

[sanesecurity]
enabled = yes

[urlhaus]
enabled = yes
max_size = 5MB
