#!/usr/bin/env python3
"""Emit/check the reviewed, static PyWayland extension bindings (no compiler).

No network, scanner, PyWayland import, or target-time generation is used. Wire
signatures are recorded here independently of upstream descriptive XML; see
WORKSPACE-BROKER.md for sources and provenance. Unused requests must retain
exact opcode positions. This is development tooling, not an installer hook.
"""
from pathlib import Path
import argparse
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'd-i/forky/hooks/target/usr/local/lib/labwc-workspace-broker/python/labwc_workspace_wayland/protocol.py'
# (name, arguments [(python name, wire type, interface, nullable)], since, destructor)
def msg(name, args=(), since=1, destroy=False):
    return [name, list(args), since, destroy]
def arg(name, kind, interface=None, nullable=False):
    return [name, kind, interface, nullable]
SPECS = [
    ('ExtWorkspaceManagerV1', 'ext_workspace_manager_v1', 1,
     [msg('commit'), msg('stop')],
     [msg('workspace_group', [arg('workspace_group', 'NewId', 'ExtWorkspaceGroupHandleV1')]),
      msg('workspace', [arg('workspace', 'NewId', 'ExtWorkspaceHandleV1')]), msg('done'), msg('finished')]),
    ('ExtWorkspaceGroupHandleV1', 'ext_workspace_group_handle_v1', 1,
     [msg('create_workspace', [arg('workspace', 'String')]), msg('destroy', destroy=True)],
     [msg('capabilities', [arg('capabilities', 'Uint')]),
      msg('output_enter', [arg('output', 'Object', 'WlOutput')]),
      msg('output_leave', [arg('output', 'Object', 'WlOutput')]),
      msg('workspace_enter', [arg('workspace', 'Object', 'ExtWorkspaceHandleV1')]),
      msg('workspace_leave', [arg('workspace', 'Object', 'ExtWorkspaceHandleV1')]), msg('removed')]),
    ('ExtWorkspaceHandleV1', 'ext_workspace_handle_v1', 1,
     [msg('destroy', destroy=True), msg('activate'), msg('deactivate'),
      msg('assign', [arg('workspace_group', 'Object', 'ExtWorkspaceGroupHandleV1')]), msg('remove')],
     [msg('id', [arg('id_', 'String')]), msg('name', [arg('name', 'String')]),
      msg('coordinates', [arg('coordinates', 'Array')]), msg('state', [arg('state', 'Uint')]),
      msg('capabilities', [arg('capabilities', 'Uint')]), msg('removed')]),
    ('ZwlrForeignToplevelManagerV1', 'zwlr_foreign_toplevel_manager_v1', 3,
     [msg('stop')],
     [msg('toplevel', [arg('toplevel', 'NewId', 'ZwlrForeignToplevelHandleV1')]), msg('finished')]),
    ('ZwlrForeignToplevelHandleV1', 'zwlr_foreign_toplevel_handle_v1', 3,
     [msg('set_maximized'), msg('unset_maximized'), msg('set_minimized'), msg('unset_minimized'),
      msg('activate', [arg('seat', 'Object', 'WlSeat')]), msg('close'),
      msg('set_rectangle', [arg('surface', 'Object', 'WlSurface'), arg('x', 'Int'), arg('y', 'Int'), arg('width', 'Int'), arg('height', 'Int')]),
      msg('destroy', destroy=True), msg('set_fullscreen', [arg('output', 'Object', 'WlOutput', True)], 2), msg('unset_fullscreen', since=2)],
     [msg('title', [arg('title', 'String')]), msg('app_id', [arg('app_id', 'String')]),
      msg('output_enter', [arg('output', 'Object', 'WlOutput')]), msg('output_leave', [arg('output', 'Object', 'WlOutput')]),
      msg('state', [arg('state', 'Array')]), msg('done'), msg('closed'),
      msg('parent', [arg('parent', 'Object', 'ZwlrForeignToplevelHandleV1', True)], 3)]),
]

def render() -> str:
    digest = hashlib.sha256(json.dumps(SPECS, separators=(',', ':')).encode()).hexdigest()
    lines = ['# Generated by tools/workspace_broker_protocols.py; do not hand-edit.',
             '# Static protocol signatures; no runtime scanner or source generation.',
             f'# Reviewed signature SHA256: {digest}',
             'from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource',
             'from pywayland.protocol.wayland import WlOutput, WlSeat, WlSurface', '']
    for cls, name, version, _, _ in SPECS:
        lines += [f'class {cls}(Interface):', f'    name = {name!r}', f'    version = {version}', '']
    for cls, _, _, requests, events in SPECS:
        for suffix, base, messages, decorator, method in (
            ('Proxy', 'Proxy', requests, 'request', '_marshal'),
            ('Resource', 'Resource', events, 'event', '_post_event'),
        ):
            lines += [f'class {cls}{suffix}({base}):', f'    interface = {cls}', '']
            for opcode, (name, args, since, destructor) in enumerate(messages):
                types = []
                for _, kind, interface, nullable in args:
                    extras = (f', interface={interface}' if interface else '') + (', nullable=True' if nullable else '')
                    types.append(f'Argument(ArgumentType.{kind}{extras})')
                if since > 1:
                    types.append(f'version={since}')
                lines += [f'    @{cls}.{decorator}({", ".join(types)})',
                          f'    def {name}(self{", " if args else ""}{", ".join(a[0] for a in args)}):',
                          f'        self.{method}({opcode}{", " if args else ""}{", ".join(a[0] for a in args)})']
                if destructor:
                    lines += ['        self._destroy()']
                lines += ['']
        lines += [f'class {cls}Global(Global):', f'    interface = {cls}', '']
    for cls, *_ in SPECS:
        lines += [f'{cls}._gen_c()', f'{cls}.proxy_class = {cls}Proxy',
                  f'{cls}.resource_class = {cls}Resource', f'{cls}.global_class = {cls}Global', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if DEST.read_text() != expected:
            raise SystemExit('workspace protocol bindings differ from reviewed signatures')
        print('workspace protocol signatures: current')
    else:
        DEST.write_text(expected)
        print(DEST.relative_to(ROOT))
