[General]
autoHide=false
launchers="show-desktop;vivaldi;foot;thunar;code;bitwarden;keepassxc;timeshift;spotify;mpv;qalculate;focuswriter;gnumeric"
position=1
screen=0
showApplicationMenu=false
showBatteryIndicator=false
showClock=true
showKeyboardLayout=false
showPager=false
showTaskManager=true
showTrash=false
showVersionChecker=false
showVolumeControl=false
showWifiManager=false
visibility=3
wantsToBeOnActiveScreen=true
