[Unit]
Wants=network-pre.target
Before=network-pre.target
After=systemd-sysctl.service

[Service]
ExecStartPre=
ExecStartPre=/usr/sbin/nft -c -f /etc/nftables.conf
ExecReload=
ExecReload=/usr/sbin/nft -c -f /etc/nftables.conf
ExecReload=/usr/sbin/nft -f /etc/nftables.conf
TimeoutStartSec=30s
TimeoutStopSec=30s
NoNewPrivileges=yes
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
