#!/bin/sh

mkdir -p /var/lib/partman
rm -f /var/lib/partman/f2fs

case "$(udpkg --print-os)" in
  linux)
    while read -r module_name _rest; do
        if [ "$module_name" = f2fs ]; then
            : >/var/lib/partman/f2fs
        fi
    done </proc/modules

    if ! [ -f /var/lib/partman/f2fs ] && modprobe f2fs >/dev/null 2>/dev/null; then
        : >/var/lib/partman/f2fs
    fi

    if ! [ -f /var/lib/partman/f2fs ] &&
       [ -r /proc/filesystems ] &&
       grep -qw f2fs /proc/filesystems; then
        : >/var/lib/partman/f2fs
    fi
    ;;
esac
