[Unit]
ConditionEnvironment=LABWC_SESSION_OWNER=desktop
ConditionEnvironment=WAYLAND_DISPLAY
ConditionEnvironment=XDG_SESSION_TYPE=wayland
After=labwc-session.target
PartOf=labwc-session.target

[Install]
WantedBy=labwc-session.target
